### ISSUE TITLE
Examples do not work, project must be updated

### ISSUE THREAD

**Issue by Radoralev** [AMontgomerie/bulgarian-nlp#3]
Error on generating tags:

![image](https://user-images.githubusercontent.com/63846873/149934436-307573ef-669c-4f4a-bc88-1f366cb6c1d7.png)

Also, imports must be updated.

I just followed the steps in the jupyter notebooks that you provided. The only thing I changed is the import from: 
`from models.postaggers import POSTagger`
to:
`from models.taggers import POSTagger`

**Comment by AMontgomerie** [comment]
Thanks for pointing that out. I've updated the examples now.
